import { Pipe, PipeTransform } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Pipe({
    name: 'translateValue',
    standalone: false,
    pure: false
})
export class TranslateValuePipe implements PipeTransform {
    private translations: { [lang: string]: { [key: string]: string } } = {
        'ar': {
            // Months
            'janvier': 'يناير', 'février': 'فبراير', 'mars': 'مارس',
            'avril': 'أبريل', 'mai': 'مايو', 'juin': 'يونيو',
            'juillet': 'يوليوز', 'août': 'غشت', 'septembre': 'شتنبر',
            'octobre': 'أكتوبر', 'novembre': 'نونبر', 'décembre': 'دجنبر',
            'oct': 'أكتوبر', 'nov': 'نونبر', 'dec': 'دجنبر',
            'jan': 'يناير', 'feb': 'فبراير', 'mar': 'مارس',
            'apr': 'أبريل', 'may': 'مايو', 'jun': 'يونيو',
            'jul': 'يوليوز', 'aug': 'غشت', 'sep': 'شتنبر',
            'january': 'يناير', 'february': 'فبراير', 'march': 'مارس',
            'april': 'أبريل', 'june': 'يونيو',
            'july': 'يوليوز', 'august': 'غشت', 'september': 'شتنبر',
            'october': 'أكتوبر', 'november': 'نونبر', 'december': 'دجنبر',
            // Languages
            'arabe': 'العربية', 'français': 'الفرنسية', 'francais': 'الفرنسية',
            'tashelhit': 'تشلحيت', 'amazigh': 'الأمازيغية',
            'anglais': 'الإنجليزية', 'espagnol': 'الإسبانية',
            'arabic': 'العربية', 'french': 'الفرنسية',
            'english': 'الإنجليزية', 'spanish': 'الإسبانية',
            'tamazight': 'الأمازيغية', 'darija': 'الدارجة',
            'berbère': 'الأمازيغية', 'berbere': 'الأمازيغية',
            
            // Destinations & Cities (Morocco)
            'jemaa el-fnaa': 'ساحة جامع الفناء',
            'hassan ii mosque': 'مسجد الحسن الثاني',
            'ait ben haddou': 'آيت بن حدو',
            'merzouga desert': 'صحراء مرزوكة',
            'ouzoud waterfalls': 'شلالات أوزود',
            'fes el bali': 'فاس البالي',
            'todgha gorges': 'مضايق تودغى',
            'dades valley': 'وادي دادس',
            'essaouira medina': 'مدينة الصويرة القديمة',
            'rabat city center': 'مركز مدينة الرباط',
            'agadir beach': 'شاطئ أكادير',
            'sefrou city': 'مدينة صفرو',
            'guelmim gate': 'باب كلميم',
            'laayoune city': 'مدينة العيون',
            'imilchil village': 'قرية إملشيل',
            'dakhla lagoon': 'بحيرة الداخلة',
            'al hoceima bay': 'خليج الحسيمة',
            'bin el ouidane lake': 'بحيرة بين الويدان',
            'oualidia lagoon': 'بحيرة الوليدية',
            'azrou cedar forest': 'غابة أرز أزرو',
            'hercules caves': 'مغارة هرقل',
            'oukaimeden resort': 'منتجع أوكايمدن',
            'saidia beach': 'شاطئ السعيدية',
            'asilah old town': 'مدينة أصيلة القديمة',
            
            'marrakech': 'مراكش',
            'casablanca': 'الدار البيضاء',
            'ouarzazate': 'ورزازات',
            'errachidia': 'الرشيدية',
            'azilal': 'أزيلال',
            'fes': 'فاس',
            'tinghir': 'تنغير',
            'boumalne dades': 'بومالن دادس',
            'essaouira': 'الصويرة',
            'rabat': 'الرباط',
            'agadir': 'أكادير',
            'kelaat mgouna': 'قلعة مكونة',
            'sefrou': 'صفرو',
            'guelmim': 'كلميم',
            'laayoune': 'العيون',
            'imilchil': 'إملشيل',
            'dakhla': 'الداخلة',
            'al hoceima': 'الحسيمة',
            'oualidia': 'الوليدية',
            'azrou': 'أزرو',
            'tangier': 'طنجة',
            'berkane': 'بركان',
            'asilah': 'أصيلة',
            'tan-tan': 'طانطان',
            'ifrane': 'إفران',
            'meknes': 'مكناس',
            'cultural': 'ثقافي',
            'nature': 'طبيعة',
            'historical': 'تاريخي',
            'religious': 'ديني',
            'fes sacred music': 'مهرجان فاس للموسيقى الروحية',
            'fes sacred music.': 'مهرجان فاس للموسيقى الروحية.',
            'mawazine': 'موازين',
            'timitar': 'تيميتار',
            'festival gnaoua': 'مهرجان كناوة',
            'spiritual music': 'موسيقى روحية',
            'spiritual music.': 'موسيقى روحية.',
            'rose harvest.': 'موسم الورد.',
            'jazz festival.': 'مهرجان الجاز.',
            'international film festival.': 'مهرجان الفيلم الدولي.',
            'cherry harvest.': 'موسم حب الملوك.',
            'nomadic heritage.': 'التراث البدوي.',
            'marathon.': 'ماراثون.',
            'traditional festival.': 'مهرجان تقليدي.',
            'unesco recognized nomadic heritage.': 'تراث بدوي معترف به من قبل اليونسكو.',
            'celebrating nature in the middle atlas.': 'الاحتفاء بالطبيعة في الأطلس المتوسط.',
            'international kitesurfing competition.': 'مسابقة دولية لركوب الأمواج.',
            'international animation film festival.': 'مهرجان دولي لأفلام التحريك.',
            'amazigh culture festival': 'مهرجان الثقافة الأمازيغية',
            'amazigh culture festival.': 'مهرجان الثقافة الأمازيغية.',
            'international music festival': 'مهرجان الموسيقى الدولي',
            'international music festival.': 'مهرجان الموسيقى الدولي.',
            'join us for this amazing cultural experience in morocco.': 'انضم إلينا في هذه التجربة الثقافية الرائعة في المغرب.',
            'trending destination': 'وجهة مشهورة',
            "l'humble citadelle légendaire et majestueuse du petit village reculé d'imilchil est nichée fièrement à plus de 2119 mètres d'altitude au cœur du haut atlas central.": "تُعد قلعة إملشيل الأسطورية والمهيبة في القرية الصغيرة النائية جوهرة في قلب الأطلس الكبير على ارتفاع 2119 مترًا.",
            "la charmante médina d'essaouira, anciennement connue sous l'illustre nom de mogador, est un joyau côtier fortifié réputé pour la mélodie de ses puissants vents marins et sa diversité culturelle vibrante.": "تعتبر مدينة الصويرة القديمة، المعروفة سابقاً بموغادور، جوهرة ساحلية محصنة تشتهر برياحها البحرية وتنوعها الثقافي.",
            "nichée magnifiquement aux hauts sommets vertigineux des imposantes montagnes du haut atlas, à près de 2 600 mètres d'altitude, la sublime oukaïmeden règne à la fois comme unique et plus haute station de ski du continent africain.": "تتربع أوكايمدن الرائعة على قمم جبال الأطلس الكبير، وتعتبر أعلى محطة تزلج في أفريقيا.",
            "imposante et solennelle, l'exubérante forêt de cèdres dorés s'établit au cœur du moyen atlas autour d'azrou.": "تستقر غابة الأرز الذهبية المهيبة في قلب الأطلس المتوسط حول مدينة أزرو.",
            "la splendeur de la cité balnéaire d'agadir, située le long du littoral atlantique éclatant du maroc, présente une résilience urbaine et humaine exceptionnellement touchante.": "تتميز روعة مدينة أكادير الشاطئية على الساحل الأطلسي بمرونة حضرية وإنسانية مؤثرة.",
            "rabat, la digne capitale politique et administrative du royaume du maroc, jouit d'une captivante fusion d'héritage médiéval musulman et de splendides plans d'urbanisme colonial harmonieux.": "تتمتع الرباط، العاصمة السياسية للمغرب، بمزيج ساحر من التراث الإسلامي والتخطيط الحضري المتناغم.",
            "les gorges du todgha (ou todra) se composent de falaises de calcaire rouge monumentales atteignant jusqu'à 300 mètres de hauteur sur les flancs orientaux des montagnes du haut atlas.": "تتكون مضايق تودغى من جرف صخرية حمراء ضخمة يصل ارتفاعها إلى 300 متر في الأطلس الكبير.",
            "brillamment surnommé familièrement la majestueuse \"perle bleue\" de la fière méditerranée orientale, la sublime station de saïdia marie somptueusement sa longue plage de sable fin d'or et d'un océan céruléen éblouissant.": "تُلقب السعيدية بـ 'الجوهرة الزرقاء' للمتوسط، وتجمع بين شاطئ ذهبي وبحر فيروزي ساحر.",
            "l'éblouissante asilah, gracieuse médina lumineuse et immaculée dressée avec hardiesse contre les vagues atlantiques, séduit les pèlerins par sa tranquillité poétique inébranlable.": "تتمتع أصيلة بمدينة بيضاء ناصعة تطل على الأطلسي، وتجذب الزوار بهدوئها وفنونها.",
            "la place jemaa el-fnaa est le cœur battant de marrakech depuis la fondation de la ville au xie siècle par les almoravides.": "تعتبر ساحة جامع الفناء القلب النابض لمراكش منذ القرن الحادي عشر.",
            "fès el-bali, la plus ancienne médina fortifiée de fès, a été fondée à la fin du viiie siècle par la dynastie idrisside.": "تأسست فاس البالي، أقدم مدينة محصنة في فاس، في نهاية القرن الثامن.",
            "oualidia, pittoresque lagune paisible dotée d'une éblouissante splendeur, se situe majestueusement sur la côte atlantique.": "تقع الوليدية، وهي بحيرة هادئة وخلابة ذات روعة مذهلة، على الساحل الأطلسي.",
            "aït-ben-haddou est un ksar du maroc inscrit sur la liste du patrimoine mondial de l'unesco depuis 1987.": "آيت بن حدو قصر مغربي مسجل في قائمة اليونسكو للتراث العالمي منذ 1987.",
            "le désert de merzouga, avec ses imposantes dunes d'erg chebbi qui peuvent atteindre jusqu'à 150 mètres de hauteur, est une merveille géologique du sud-est marocain.": "صحراء مرزوكة بكثبانها الرملية العالية هي أعجوبة جيولوجية في الجنوب الشرقي."
        },
        'en': {
            'janvier': 'January', 'février': 'February', 'fevrier': 'February', 'mars': 'March',
            'avril': 'April', 'mai': 'May', 'juin': 'June',
            'juillet': 'July', 'août': 'August', 'aout': 'August', 'septembre': 'September',
            'octobre': 'October', 'novembre': 'November', 'décembre': 'December', 'decembre': 'December',
            'oct': 'Oct', 'nov': 'Nov', 'dec': 'Dec',
            'arabe': 'Arabic', 'français': 'French', 'francais': 'French',
            'tashelhit': 'Tashelhit', 'amazigh': 'Amazigh',
            'anglais': 'English', 'espagnol': 'Spanish',
            'darija': 'Darija', 'berbère': 'Berber', 'berbere': 'Berber',
            'cultural': 'Cultural', 'nature': 'Nature', 'historical': 'Historical', 'religious': 'Religious',
            'fes': 'Fes', 'marrakech': 'Marrakech', 'casablanca': 'Casablanca', 'agadir': 'Agadir', 'rabat': 'Rabat', 'tangier': 'Tangier', 'tanger': 'Tangier', 'essaouira': 'Essaouira',
            'fes sacred music': 'Fes Sacred Music',
            'fes sacred music.': 'Fes Sacred Music.',
            'mawazine': 'Mawazine',
            'timitar': 'Timitar',
            'festival gnaoua': 'Gnaoua Festival',
            'spiritual music': 'Spiritual Music',
            'spiritual music.': 'Spiritual Music.',
            'rose harvest.': 'Rose harvest.',
            'jazz festival.': 'Jazz festival.',
            'international film festival.': 'International Film Festival.',
            'cherry harvest.': 'Cherry harvest.',
            'nomadic heritage.': 'Nomadic heritage.',
            'marathon.': 'Marathon.',
            'traditional festival.': 'Traditional festival.',
            'unesco recognized nomadic heritage.': 'UNESCO recognized nomadic heritage.',
            'celebrating nature in the middle atlas.': 'Celebrating nature in the Middle Atlas.',
            'international kitesurfing competition.': 'International kitesurfing competition.',
            'international animation film festival.': 'International animation film festival.',
            'amazigh culture festival': 'Amazigh Culture Festival',
            'amazigh culture festival.': 'Amazigh Culture Festival.',
            'international music festival': 'International Music Festival',
            'international music festival.': 'International Music Festival.',
            'join us for this amazing cultural experience in morocco.': 'Join us for this amazing cultural experience in Morocco.',
            'trending destination': 'Trending destination',
            "l'humble citadelle légendaire et majestueuse du petit village reculé d'imilchil est nichée fièrement à plus de 2119 mètres d'altitude au cœur du haut atlas central.": "The legendary and majestic citadel of the remote village of Imilchil is nestled proudly at over 2119 meters altitude in the heart of the High Atlas.",
            "la charmante médina d'essaouira, anciennement connue sous l'illustre nom de mogador, est un joyau côtier fortifié réputé pour la mélodie de ses puissants vents marins et sa diversité culturelle vibrante.": "The charming medina of Essaouira, formerly known as Mogador, is a fortified coastal jewel renowned for its sea winds and vibrant cultural diversity.",
            "nichée magnifiquement aux hauts sommets vertigineux des imposantes montagnes du haut atlas, à près de 2 600 mètres d'altitude, la sublime oukaïmeden règne à la fois comme unique et plus haute station de ski du continent africain.": "Magnificently nestled in the high peaks of the High Atlas, at nearly 2,600 meters, the sublime Oukaimeden is Africa's highest ski resort.",
            "imposante et solennelle, l'exubérante forêt de cèdres dorés s'établit au cœur du moyen atlas autour d'azrou.": "Imposing and solemn, the exuberant golden cedar forest is established in the heart of the Middle Atlas around Azrou.",
            "la splendeur de la cité balnéaire d'agadir, située le long du littoral atlantique éclatant du maroc, présente une résilience urbaine et humaine exceptionnellement touchante.": "The splendor of Agadir, located along the vibrant Atlantic coast, presents an exceptionally touching urban and human resilience.",
            "rabat, la digne capitale politique et administrative du royaume du maroc, jouit d'une captivante fusion d'héritage médiéval musulman et de splendides plans d'urbanisme colonial harmonieux.": "Rabat, the political capital of Morocco, enjoys a captivating fusion of Muslim medieval heritage and harmonious colonial urban planning.",
            "les gorges du todgha (ou todra) se composent de falaises de calcaire rouge monumentales atteignant jusqu'à 300 mètres de hauteur sur les flancs orientaux des montagnes du haut atlas.": "The Todgha Gorges consist of monumental red limestone cliffs reaching up to 300 meters on the eastern flanks of the High Atlas.",
            "brillamment surnommé familièrement la majestueuse \"perle bleue\" de la fière méditerranée orientale, la sublime station de saïdia marie somptueusement sa longue plage de sable fin d'or et d'un océan céruléen éblouissant.": "Brilliantly nicknamed the 'Blue Pearl' of the Mediterranean, the sublime resort of Saidia marries a long golden beach with a dazzling ocean.",
            "l'éblouissante asilah, gracieuse médina lumineuse et immaculée dressée avec hardiesse contre les vagues atlantiques, séduit les pèlerins par sa tranquillité poétique inébranlable.": "Dazzling Asilah, a graceful and immaculate medina stood against Atlantic waves, seduces pilgrims with its unwavering poetic tranquility.",
            "la place jemaa el-fnaa est le cœur battant de marrakech depuis la fondation de la ville au xie siècle par les almoravides.": "Jemaa el-Fnaa square has been the beating heart of Marrakech since the 11th century.",
            "fès el-bali, la plus ancienne médina fortifiée de fès, a été fondée à la fin du viiie siècle par la dynastie idrisside.": "Fes el-Bali, the oldest fortified medina in Fes, was founded at the end of the 8th century.",
            "oualidia, pittoresque lagune paisible dotée d'une éblouissante splendeur, se situe majestueusement sur la côte atlantique.": "Oualidia, a picturesque and peaceful lagoon with dazzling splendor, is majestically located on the Atlantic coast.",
            'imilchil village': 'Imilchil Village', 'essaouira medina': 'Essaouira Medina', 'oukaimeden resort': 'Oukaimeden Resort', 'azrou cedar forest': 'Azrou Cedar Forest', 'todgha gorges': 'Todgha Gorges', 'agadir beach': 'Agadir Beach', 'saidia beach': 'Saidia Beach', 'rabat city center': 'Rabat City Center'
        },
        'es': {
            'janvier': 'Enero', 'février': 'Febrero', 'fevrier': 'Febrero', 'mars': 'Marzo',
            'avril': 'Abril', 'mai': 'Mayo', 'juin': 'Junio',
            'juillet': 'Julio', 'août': 'Agosto', 'aout': 'Agosto', 'septembre': 'Septiembre',
            'octobre': 'Octubre', 'novembre': 'Noviembre', 'décembre': 'Diciembre', 'decembre': 'Diciembre',
            'oct': 'Oct', 'nov': 'Nov', 'dec': 'Dic',
            'arabe': 'Árabe', 'français': 'Francés', 'francais': 'Francés',
            'tashelhit': 'Tashelhit', 'amazigh': 'Amazigh',
            'anglais': 'Inglés', 'espagnol': 'Español',
            'darija': 'Darija', 'berbère': 'Bereber', 'berbere': 'Bereber',
            'cultural': 'Cultural', 'nature': 'Naturaleza', 'historical': 'Histórico', 'religious': 'Religioso',
            'fes': 'Fez', 'marrakech': 'Marrakech', 'casablanca': 'Casablanca', 'agadir': 'Agadir', 'rabat': 'Rabat', 'tangier': 'Tánger', 'tanger': 'Tánger', 'essaouira': 'Esauira',
            'fes sacred music': 'Festival de Músicas Sacras de Fez',
            'fes sacred music.': 'Festival de Músicas Sacras de Fez.',
            'mawazine': 'Mawazine',
            'timitar': 'Timitar',
            'festival gnaoua': 'Festival de Gnaoua',
            'spiritual music': 'Música espiritual',
            'spiritual music.': 'Música espiritual.',
            'rose harvest.': 'Cosecha de rosas.',
            'jazz festival.': 'Festival de jazz.',
            'international film festival.': 'Festival internacional de cine.',
            'cherry harvest.': 'Cosecha de cerezas.',
            'nomadic heritage.': 'Patrimonio nómada.',
            'marathon.': 'Maratón.',
            'traditional festival.': 'Festival tradicional.',
            'unesco recognized nomadic heritage.': 'Patrimonio nómada reconocido por la UNESCO.',
            'celebrating nature in the middle atlas.': 'Celebrando la naturaleza en el Atlas Medio.',
            'international kitesurfing competition.': 'Competición internacional de kitesurf.',
            'international animation film festival.': 'Festival internacional de cine de animación.',
            'amazigh culture festival': 'Festival de cultura amazigh',
            'amazigh culture festival.': 'Festival de cultura amazigh.',
            'international music festival': 'Festival internacional de música',
            'international music festival.': 'Festival internacional de música.',
            'join us for this amazing cultural experience in morocco.': 'Únete a nosotros para esta increíble experiencia cultural en Marruecos.',
            'trending destination': 'Destino de tendencia',
            "l'humble citadelle légendaire et majestueuse du petit village reculé d'imilchil est nichée fièrement à plus de 2119 mètres d'altitude au cœur du haut atlas central.": "La legendaria ciudadela de Imilchil está situada a más de 2119 metros de altitud en el corazón del Gran Atlas.",
            "la charmante médina d'essaouira, anciennement connue sous l'illustre nom de mogador, est un joyau côtier fortifié réputé pour la mélodie de ses puissants vents marins et sa diversité culturelle vibrante.": "La medina de Essaouira, antes Mogador, es una joya costera famosa por sus vientos y su diversidad cultural.",
            "nichée magnifiquement aux hauts sommets vertigineux des imposantes montagnes du haut atlas, à près de 2 600 mètres d'altitude, la sublime oukaïmeden règne à la fois comme unique et plus haute station de ski du continent africain.": "Situada en las cumbres del Gran Atlas, Oukaimeden es la estación de esquí más alta de África.",
            "imposante et solennelle, l'exubérante forêt de cèdres dorés s'établit au cœur du moyen atlas autour d'azrou.": "El majestuoso bosque de cedros dorados se encuentra en el Atlas Medio, cerca de Azrou.",
            "la splendeur de la cité balnéaire d'agadir, située le long du littoral atlantique éclatant du maroc, présente une résilience urbaine et humaine exceptionnellement touchante.": "Agadir, en la costa atlántica, muestra una resistencia urbana y humana muy emocionante.",
            "rabat, la digne capitale politique et administrative du royaume du maroc, jouit d'une captivante fusion d'héritage médiéval musulman et de splendides plans d'urbanisme colonial harmonieux.": "Rabat, capital de Marruecos, une el patrimonio medieval con un urbanismo colonial armonioso.",
            "les gorges du todgha (ou todra) se composent de falaises de calcaire rouge monumentales atteignant jusqu'à 300 mètres de hauteur sur les flancs orientaux des montagnes du haut atlas.": "Las Gargantas del Todra tienen acantilados de caliza roja de 300 metros en el Atlas Gran.",
            "brillamment surnommé familièrement la majestueuse \"perle bleue\" de la fière méditerranée orientale, la sublime station de saïdia marie somptueusement sa longue plage de sable fin d'or et d'un océan céruléen éblouissant.": "Saidia, la 'Perla Azul', une una playa dorada con un mar azul deslumbrante.",
            "l'éblouissante asilah, gracieuse médina lumineuse et immaculée dressée avec hardiesse contre les vagues atlantiques, séduit les pèlerins par sa tranquillité poétique inébranlable.": "Asilah es una medina blanca frente al Atlántico, famosa por su calma y sus murales artísticos.",
            "la place jemaa el-fnaa est le cœur battant de marrakech depuis la fondation de la ville au xie siècle par les almoravides.": "La plaza Jemaa el-Fnaa es el corazón de Marrakech desde el siglo XI.",
            "fès el-bali, la plus ancienne médina fortifiée de fès, a été fondée à la fin du viiie siècle par la dynastie idrisside.": "Fez el-Bali, la medina amurallada más antigua de Fez, fue fundada a finales del siglo VIII.",
            "oualidia, pittoresque lagune paisible dotée d'une éblouissante splendeur, se situe majestueusement sur la côte atlantique.": "Oualidia, pintoresca laguna tranquila de deslumbrante esplendor, se encuentra en la costa atlántica.",
            'imilchil village': 'Pueblo de Imilchil', 'essaouira medina': 'Medina de Essaouira', 'oukaimeden resort': 'Estación de Oukaimeden', 'azrou cedar forest': 'Bosque de cedros de Azrou', 'todgha gorges': 'Gargantas del Todra', 'agadir beach': 'Playa de Agadir', 'saidia beach': 'Playa de Saidia', 'rabat city center': 'Centro de la ciudad de Rabat'
        },
        'fr': {
            'january': 'janvier', 'february': 'février', 'march': 'mars',
            'april': 'avril', 'may': 'mai', 'june': 'juin',
            'july': 'juillet', 'august': 'août', 'september': 'septembre',
            'october': 'octobre', 'november': 'novembre', 'december': 'décembre',
            'arabic': 'arabe', 'french': 'français', 'english': 'anglais', 'spanish': 'espagnol',
            'berber': 'berbère',
            'fes': 'Fès', 'marrakech': 'Marrakech', 'casablanca': 'Casablanca', 'agadir': 'Agadir', 'rabat': 'Rabat', 'tangier': 'Tanger', 'tanger': 'Tanger', 'essaouira': 'Essaouira',
            'fes sacred music': 'Festival des Musiques Sacrées',
            'fes sacred music.': 'Festival des Musiques Sacrées.',
            'mawazine': 'Mawazine',
            'timitar': 'Timitar',
            'festival gnaoua': 'Festival Gnaoua',
            'spiritual music': 'Musique spirituelle',
            'spiritual music.': 'Musique spirituelle.',
            'rose harvest.': 'Récolte des roses.',
            'jazz festival.': 'Festival de jazz.',
            'international film festival.': 'Festival international du film.',
            'cherry harvest.': 'Récolte des cerises.',
            'nomadic heritage.': 'Héritage nomade.',
            'marathon.': 'Marathon.',
            'traditional festival.': 'Festival traditionnel.',
            'unesco recognized nomadic heritage.': 'Héritage nomade reconnu par l\'UNESCO.',
            'celebrating nature in the middle atlas.': 'Célébrer la nature dans le Moyen Atlas.',
            'international kitesurfing competition.': 'Compétition internationale de kitesurf.',
            'international animation film festival.': 'Festival international du cinéma d\'animation.',
            'amazigh culture festival': 'Festival de la culture amazighe',
            'amazigh culture festival.': 'Festival de la culture amazighe.',
            'international music festival': 'Festival international de musique',
            'international music festival.': 'Festival international de musique.',
            'join us for this amazing cultural experience in morocco.': 'Rejoignez-nous pour cette incroyable expérience culturelle au Maroc.',
            'trending destination': 'Destination tendance',
            "l'humble citadelle légendaire et majestueuse du petit village reculé d'imilchil est nichée fièrement à plus de 2119 mètres d'altitude au cœur du haut atlas central.": "L'humble citadelle légendaire et majestueuse du petit village reculé d'Imilchil est nichée fièrement à plus de 2119 mètres d'altitude au cœur du Haut Atlas central.",
            "la charmante médina d'essaouira, anciennement connue sous l'illustre nom de mogador, est un joyau côtier fortifié réputé pour la mélodie de ses puissants vents marins et sa diversité culturelle vibrante.": "La charmante médina d'Essaouira, anciennement connue sous l'illustre nom de Mogador, est un joyau côtier fortifié réputé pour la mélodie de ses puissants vents marins et sa diversité culturelle vibrante.",
            "nichée magnifiquement aux hauts sommets vertigineux des imposantes montagnes du haut atlas, à près de 2 600 mètres d'altitude, la sublime oukaïmeden règne à la fois comme unique et plus haute station de ski du continent africain.": "Nichée magnifiquement aux hauts sommets vertigineux des imposantes montagnes du Haut Atlas, à près de 2 600 mètres d'altitude, la sublime Oukaïmeden règne à la fois comme unique et plus haute station de ski du continent africain.",
            "imposante et solennelle, l'exubérante forêt de cèdres dorés s'établit au cœur du moyen atlas autour d'azrou.": "Imposante et solennelle, l'exubérante forêt de cèdres dorés s'établit au cœur du Moyen Atlas autour d'Azrou.",
            "la splendeur de la cité balnéaire d'agadir, située le long du littoral atlantique éclatant du maroc, présente une résilience urbaine et humaine exceptionnellement touchante.": "La splendeur de la cité balnéaire d'Agadir, située le long du littoral atlantique éclatant du Maroc, présente une résilience urbaine et humaine exceptionnellement touchante.",
            "rabat, la digne capitale politique et administrative du royaume du maroc, jouit d'une captivante fusion d'héritage médiéval musulman et de splendides plans d'urbanisme colonial harmonieux.": "Rabat, la digne capitale politique et administrative du Royaume du Maroc, jouit d'une captivante fusion d'héritage médiéval musulman et de splendides plans d'urbanisme colonial harmonieux.",
            "les gorges du todgha (ou todra) se composent de falaises de calcaire rouge monumentales atteignant jusqu'à 300 mètres de hauteur sur les flancs orientaux des montagnes du haut atlas.": "Les gorges du Todgha (ou Todra) se composent de falaises de calcaire rouge monumentales atteignant jusqu'à 300 mètres de hauteur sur les flancs orientaux des montagnes du Haut Atlas.",
            "brillamment surnommé familièrement la majestueuse \"perle bleue\" de la fière méditerranée orientale, la sublime station de saïdia marie somptueusement sa longue plage de sable fin d'or et d'un océan céruléen éblouissant.": "Brillamment surnommé familièrement la majestueuse \"Perle Bleue\" de la fière Méditerranée orientale, la sublime station de Saïdia marie somptueusement sa longue plage de sable fin d'or et d'un océan céruléen éblouissant.",
            "l'éblouissante asilah, gracieuse médina lumineuse et immaculée dressée avec hardiesse contre les vagues atlantiques, séduit les pèlerins par sa tranquillité poétique inébranlable.": "L'éblouissante Asilah, gracieuse médina lumineuse et immaculée dressée avec hardiesse contre les vagues atlantiques, séduit les pèlerins par sa tranquillité poétique inébranlable.",
            "la place jemaa el-fnaa est le cœur battant de marrakech depuis la fondation de la ville au xie siècle par les almoravides.": "La place Jemaa el-Fnaa est le cœur battant de Marrakech depuis la fondation de la ville au XIe siècle par les Almoravides.",
            "fès el-bali, la plus ancienne médina fortifiée de fès, a été fondée à la fin du viiie siècle par la dynastie idrisside.": "Fès el-Bali, la plus ancienne médina fortifiée de Fès, a été fondée à la fin du VIIIe siècle par la dynastie idrisside.",
            "oualidia, pittoresque lagune paisible dotée d'une éblouissante splendeur, se situe majestueusement sur la côte atlantique.": "Oualidia, pittoresque lagune paisible dotée d'une éblouissante splendeur, se situe majestueusement sur la côte atlantique.",
            'imilchil village': "Village d'Imilchil", 'essaouira medina': "Médina d'Essaouira", 'oukaimeden resort': "Station d'Oukaïmeden", 'azrou cedar forest': "Forêt de cèdres d'Azrou", 'todgha gorges': 'Gorges du Todgha', 'agadir beach': 'Plage d\'Agadir', 'saidia beach': 'Plage de Saïdia', 'rabat city center': 'Centre-ville de Rabat'
        }
    };

    constructor(private translate: TranslateService) {}

    transform(value: string | undefined | null, fallbackKey?: string): string {
        if (!value && fallbackKey) {
            return this.translate.instant(fallbackKey);
        }
        if (!value) return '';

        const lang = this.translate.currentLang || this.translate.defaultLang || 'en';
        const map = this.translations[lang];
        if (!map) return value;

        // Check if the entire string (lowercased) exists in the map
        const fullMatch = map[value.toLowerCase()];
        if (fullMatch) {
            return fullMatch;
        }

        // Split by common separators, translate each part, rejoin
        return value.replace(/[\wÀ-ÿ-]+/gi, (word) => {
            const lower = word.toLowerCase();
            return map[lower] || word;
        });
    }
}
